### ISSUE TITLE
Team 2 Schedule

### ISSUE THREAD

**Issue by AudreyZone4** [kevinli96/BCG-Zone-4#9]
Tabelize the Excel Team 2 Schedule and add to our site
Also add the pdf version for printing.  
I am experimenting with adding the files to this issue (you already have the same file from the USB key last Thursday.

[2018 Team 2 Schedule.xlsx](https://github.com/kevinli96/BCG-Zone-4/files/1632993/2018.Team.2.Schedule.xlsx)
[secondteam.pdf](https://github.com/kevinli96/BCG-Zone-4/files/1632995/secondteam.pdf)

**Comment by SherryZone4** [comment]
Waiting for comments from Audrey and Kevin about format.

**Comment by AudreyZone4** [comment]
Hi Sherry and Kevin

Sorry for the delay in responding, I took the night off and we went to the Chinese Lantern Festival last night. 

 

I have finally been successful at setting up Team 1 using Tableizer so we can compare one to the other.  

·       Team 1 is very simple, I did not include the header lines or anything fancy other than I selected approximately the same colour as Sherry for the header, but it only did the side not the top.  I may not have done it correctly, but it was easy once I figured it out and I could get my cache to refresh.  

·       Sherry, I like what you have done with Team 2 – it is very nice with the bolding, colour and dark borders, but I worry about how much extra work it is to do this.  I glanced at the code and there is a lot more in yours than mine.  

·       Sherry, on your table, I like having the 2018 Team 2 Schedule header line because it is a confirmation that it is the latest schedule.  My Team 1 schedule has no confirmation of this.  

·       I don’t think it is necessary to have the Team 2 Chair and email address at the bottom because it displays just above the schedule.  I didn’t include these lines or the header date line when I copied things into Tableizer so I am not sure what it would have done.  

·       Kevin, how do you reformat the code to make it indented again? 

·       My thoughts are that either is acceptable, Sherry’s is “prettier” but II think it depends on the difficulty and what Kevin thinks of the code.  

We should leave Team 3 and the Business Women until we agree on a format.  

Cheers

Audrey

**Comment by SherryZone4** [comment]
Team2 is complete except for some H to and A at not having any colour
